#!/bin/bash

cd /usr/lib/hobot-gpio
which python3 > /dev/null
if [ $? -ne 0 ];then
    echo -e "Please apt install python3 first and then reinstall this package!"
    cd -
    exit 0
fi
/usr/bin/python3 ./setup.py install > /dev/null 2>&1
cd - > /dev/null
exit 0
